Don't disable ERTM if kernel 5.12 or later
atar-axis/xpadneo pull request #288
Opened 2021-04-29 17:08 UTC by Mikaka27

Removed disabling of ERTM only from dkms.post_install, I left dkms.post_remove alone. Reasoning for this was, that user could have installed xpadneo on older kernel, updated their kernel to 5.12 or later, and did an "sudo ./update.sh", which has to remove old ERTM override.

2021-04-29 17:22 UTC, kakra requested changes
My suggestion makes it easier to compare against multiple versions, in fact, if the L2CAP patch would be back-ported, you could just check a range `5010xxx..5011000` (would require to add the third version component).

2021-04-29 17:22 UTC, kakra commented on hid-xpadneo/dkms.post_install
> +if [ "$KERNEL_MAJOR" -ge 6 ] || ([ "$KERNEL_MAJOR" -ge 5 ] && [ "$KERNEL_MINOR" -ge 12 ]); then
I'd probably use something like `uname -r | awk -F. '{ printf "%03d%03d",$1,$2 }'` and compare against `005012`.

2021-04-29 18:53 UTC, Mikaka27 commented
I've updated the pull request according to your comments. It's better that way.

2021-04-30 01:59 UTC, kakra approved these changes
LGTM

2021-04-30 12:31 UTC, kakra commented
Can you squash both commits?

2021-04-30 12:49 UTC, Mikaka27 commented
Just did :)

2021-05-01 06:52 UTC, merged