Add configuration for disabling chords
atar-axis/xpadneo pull request #435
Opened 2023-07-18 20:24 UTC by BoukeHaarsma23

For use with steam, the button chord guide + A is mapped to the QAM. To not lose the profile switching behavior let the user configure this.

closes #419

2023-07-18 20:34 UTC, kakra commented on hid-xpadneo/src/hid-xpadneo.c
> +		if (!param_disable_button_chords) {
I think if you swapped both if statements, you won't need to report the key in the else branch.

2023-07-18 20:37 UTC, kakra commented on docs/CONFIGURATION.md
> +* 'disable_chords' (default 0)
While I get where "chord" comes from, I'm not sure if this is the correct word here - but I'm not a native speaker. Maybe it should be renamed to `disable_shift_mode`: It shifts the operation of the buttons to a different operation - just like the shift key on your keyboard.

2023-07-18 20:39 UTC, kakra commented on docs/CONFIGURATION.md
> +  * '0' will cache XBOX button presses for profile switching
We used "Xbox logo button" in other places.

2023-07-18 20:39 UTC, kakra commented on hid-xpadneo/src/hid-xpadneo.c
> +		"(bool) Disable button chords with XBOX button. Will prohibit profile switching when enabled. "
Same here, "Xbox logo button"

2023-07-18 20:43 UTC, kakra commented on docs/CONFIGURATION.md
> +  * '1' will disable XBOX button chords and will pass them through without caching
I think we should avoid programming-speech here and just say "pass it through as-is". Also, the sentence is wrong: we won't pass "chords" through, we pass all buttons through as-is in the disabled case.

2023-07-18 20:45 UTC, kakra commented on hid-xpadneo/src/hid-xpadneo.c
> +		if (!param_disable_button_chords) {
Or rather combine both if's via `&&`.

2023-07-18 20:51 UTC, kakra commented on hid-xpadneo/src/hid-xpadneo.c
> +			input_report_key(gamepad, BTN_XBOX, value);
This is missing the sync event because it ends in stop_processing. But the else branch is not needed at all if you join both if statements above.

2023-07-18 21:20 UTC, kakra requested changes
Looks almost good, I'll need to figure out how to fix the CI failing. I may need to merge your PR manually with some amends if you don't mind.

2023-07-18 21:20 UTC, kakra commented on docs/CONFIGURATION.md
> +  * Let's you disable the button chords used with the XBOX button
It still has the chords here and no Xbox logo button

2023-07-18 21:20 UTC, kakra commented on hid-xpadneo/src/hid-xpadneo.c
> +		"(bool) Disable use Xbox logo button as shift. Will prohibit profile switching when enabled. "
For some reason, the CI pipeline will freak out here. I'll solve that locally.

2023-07-19 08:48 UTC, kakra approved these changes

2024-02-22 23:54 UTC, kakra approved these changes
Merged into patch queue. This needs re-testing with the CI.

2024-02-23 00:08 UTC, kakra commented
@BoukeHaarsma23 I fixed the CI bug, there was a superfluous `A` in `MODULE_PARAM_DESC` where it really should be `MODULE_PARM_DESC`. No idea why my local compiler just accepted it (and yours probably did, too), the CI did not. It's fixed now and queued in my patch queue for testing. This PR will automatically close once I merged it.

2024-04-13 19:40 UTC, anthr76 commented
Will this get merged?

2024-04-14 00:25 UTC, kakra commented
Sorry, I completely forgot about this. I've put it into my local testing branch now to see if there are no side effects.

2024-04-22 22:15 UTC, closed without merging